# Generated by Django 5.0.2 on 2024-04-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('poster', models.ImageField(upload_to='images/')),
                ('space', models.FloatField()),
                ('has_ventilation', models.BooleanField(default=False)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_storage', models.BooleanField(default=False)),
                ('has_waitingarea', models.BooleanField(default=False)),
                ('loc_latitude', models.FloatField()),
                ('loc_longitude', models.FloatField()),
                ('price', models.FloatField()),
                ('period', models.CharField(choices=[('Annually', 'Annually')], max_length=100)),
                ('status', models.CharField(choices=[('rejected', 'Rejected')], max_length=100)),
                ('equipment', models.ManyToManyField(to='KitchenOwner.equipment')),
                ('kitchen_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.kitchenowner')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KitchenOwner.kitchen')),
            ],
        ),
    ]
