# Generated by Django 5.0.2 on 2024-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='equipment',
            name='icon',
            field=models.CharField(default='', max_length=64),
        ),
    ]
