# Generated by Django 5.0.2 on 2024-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0002_remove_equipment_quantity_equipment_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Annually', 'Annually')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=100),
        ),
    ]
