# Generated by Django 5.0.2 on 2024-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0003_alter_kitchen_period_alter_kitchen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
