# Generated by Django 5.0.4 on 2024-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0003_alter_kitchen_period_alter_kitchen_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='poster',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images/'),
        ),
    ]
