# Generated by Django 5.0.4 on 2024-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0005_rename_poster_kitchen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='posters/no_image.jpg', upload_to='posters/'),
        ),
    ]
