# Generated by Django 5.0.2 on 2024-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0007_alter_kitchen_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='poster',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='posters/no_image.jpg', upload_to='posters/'),
        ),
    ]
