# Generated by Django 5.0.4 on 2024-04-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0006_alter_kitchen_image'),
        ('KitchenOwner', '0007_alter_kitchen_city'),
    ]

    operations = [
    ]
