# Generated by Django 5.0.4 on 2024-04-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0002_remove_equipment_quantity_equipment_icon'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='kitchen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='KitchenOwner.kitchen'),
            preserve_default=False,
        ),
    ]
