# Generated by Django 5.0.2 on 2024-04-23 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KitchenOwner', '0001_initial'),
        ('Renters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFavorit',
            new_name='BookMark',
        ),
    ]
