# Generated by Django 5.0.4 on 2024-04-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0002_rename_myfavorit_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('مقبولة', 'مقبولة'), ('مرفوضة', 'مرفوضة'), ('تحت المراحعة', 'تحت المراحعة'), ('مدفوعة', 'مدفوعة')], max_length=64),
        ),
    ]
