# Generated by Django 5.0.4 on 2024-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0004_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('مقبولة', 'مقبولة'), ('مرفوضة', 'مرفوضة'), ('تحت المراجعة', 'تحت المراجعة'), ('مدفوعة', 'مدفوعة')], max_length=64),
        ),
    ]
