# Generated by Django 5.0.4 on 2024-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_year',
            field=models.DateField(null=True),
        ),
    ]
