# Generated by Django 5.0.4 on 2024-04-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Renters', '0006_order_price'),
        ('Renters', '0006_remove_payment_expired_date_order_price_and_more'),
    ]

    operations = [
    ]
