# Generated by Django 5.0.2 on 2024-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenowner',
            name='commercial_register',
            field=models.FileField(upload_to='files/'),
        ),
    ]
