# Generated by Django 5.0.4 on 2024-04-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_chife_avatar_alter_kitchenowner_avatar_and_more'),
        ('accounts', '0002_alter_kitchenowner_commercial_register'),
    ]

    operations = [
    ]
