# Generated by Django 5.0.4 on 2024-04-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20240426_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenowner',
            name='commercial_register',
            field=models.FileField(upload_to=''),
        ),
    ]
